version: '3.7'

services:
    nginx:
        image: nginx:1.17
        ports:
            - 84:80
        restart: always
        depends_on:
            - php
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
    php:
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=kdvorDocker"
        depends_on:
            - mongo
            - mysql
        volumes:
          - ./:/app
    mongo:
        image: mongo:4
        restart: always
        ports:
            - 27017:27017
        volumes:
          - mongo-data:/data/db
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: kdvor
            MYSQL_ROOT_PASSWORD: example
        volumes:
          - mysql-data:/var/lib/mysql
volumes:
    mysql-data:
    mongo-data:
